### ISSUE TITLE
Missing examples.

### ISSUE THREAD

**Issue by knarkzel** [rust-wii/ogc-rs#19]
`ogc-rs` currently only has one example which resides in another repository. `ogc-rs` should have examples included in its repository, making it easier to figure out how to use it. I have ported ProfElements' `embedded_graphics` to pure `ogc-rs` functions: https://github.com/knarkzel/rogue. I'd also recommend restructuring the repository such that the structure looks like this:

```
ogc-rs
|-- Cargo.lock
|-- Cargo.toml
|-- LICENSE
|-- README.md
|-- examples
|-- ogc-sys
|   |-- Cargo.toml
|   |-- build.rs
|   |-- src
|   `-- wrapper.h
|-- powerpc-unknown-eabi.json
`-- src
    |-- audio.rs
    |-- console.rs
    |-- debug.rs
    |-- error.rs
    |-- gu.rs
    |-- gx.rs
    |-- lib.rs
    |-- network.rs
    |-- runtime.rs
    |-- system.rs
    |-- utils.rs
    `-- video.rs
```

This way, we can easily add examples without getting errors because of "virtual Cargo.toml manifesto...".

**Comment by FrictionlessPortals** [comment]
After #28 the main example template has been added, I will close this issue for now as future examples can be added through PRs.
