### ISSUE TITLE
ogc-sys's `Mtx34` and `Mtx44` should have wrapper type in ogc-rs

### ISSUE THREAD

**Issue by ProfElements** [rust-wii/ogc-rs#30]

**Comment by knarkzel** [comment]
Hmm. So basically a `Mtx` type which is basically a `Mtx44` which can be used as a `Mtx34`?

**Comment by ProfElements** [comment]
I mean I have to directly access ffi to have those type would rather not have to do that

**Comment by ProfElements** [comment]
This is kinda implemented with 765422d. Will have to do more to properly implement this stuff.

**Comment by ProfElements** [comment]
Fixed in 765422d
