### ISSUE TITLE
Enhancement: Input can be more useful.

### ISSUE THREAD

**Issue by ProfElements** [rust-wii/ogc-rs#34]
This mostly entails making it into 3 parts.
Input,
Pad,
Wpad,

All eould be seperate modules.
Input pub externing the Pad and Wpad structures.

**Comment by knarkzel** [comment]
I believe having both `pad` and `wpad` as seperate modules following the `libogc` API directly is better than wrapping it all inside one module. There should then be a `input` module as a wrapper on top of both `pad` and `wpad`.

**Comment by ProfElements** [comment]
its already a thin wrapped around pad and WPad. You can directly init, update, and get buttons via ControllerPort seperately. see `Gamepad` and `Wiipad` structures in `input.rs`

**Comment by ProfElements** [comment]
Fixed by #52.
