### ISSUE TITLE
Voladdress yanked, breaking ogc-rs dependency fetch

### ISSUE THREAD

**Issue by LucvandenBrand** [rust-wii/ogc-rs#75]
[Voladdress](https://crates.io/crates/voladdress/versions) has yanked a lot of versions, causing errors on fetching ogc-rs as a dependency as well. Hopefully nothing breaks compatibility, but it would be good to update that dependency to v1.2.2 (latest).

**Comment by Daxorinator** [comment]
Resolved by #76, thanks for your contribution :)
