### ISSUE TITLE
Cannot compile the exemple

### ISSUE THREAD

**Issue by antoineok** [rust-wii/ogc-rs#82]
Hello, I get some problem when compiling the example (template) and i get a lot of error while compiling the template example due to a lot of errors. The error is always the same, but for differents lib.

The whole log:
https://hastebin.com/share/ruyuzulexa.wasm

The command used:
cargo +nightly build -Zbuild-std=core,alloc --target powerpc-unknown-eabi.json

the error (which stays the same):

= note: /opt/devkitpro/devkitPPC/powerpc-eabi/bin/ld: unrecognised emulation mode: elf_x86_64
          Supported emulations: elf32ppc elf32ppclinux elf32ppcsim elf32lppc elf32lppclinux elf32lppcsim elf64ppc elf64lppc
          collect2: error: ld returned 1 exit status

**Comment by ProfElements** [comment]
i dont think this is an ogc-rs issue specifically, can you build any of the libogc examples

**Comment by Daxorinator** [comment]
Yeah I believe the same - somehow your emulation mode is set to one that doesn't exist, but I've never actually come across this option. I would have to imagine this is a configuration issue with how your install of devkitPPC is set up, I did look it up but couldn't really find anything specific to this. I have seen with other toolchains that sometimes this can happen due to bad permissions when setting up the toolchain or extracting components of it from an archive, could this be what happened here?

If you can figure out how to change the option I think elf32ppc is the right option.

**Comment by antoineok** [comment]
compiling the sockettest wii example (which uses libogc) have no problem compiling

**Comment by antoineok** [comment]
i just have a question, which ld should be used?
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-ld
or
/opt/devkitpro/devkitPPC/powerpc-eabi/bin/ld

**Comment by antoineok** [comment]
because this error is caused when /opt/devkitpro/devkitPPC/powerpc-eabi/bin is in the path

**Comment by ProfElements** [comment]
devkitpro/devkitppc/bin/ld

**Comment by antoineok** [comment]
Alright, because i am getting another error with this one

**Comment by antoineok** [comment]
= note: /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-vfprintf.o): in function `_vfprintf_r':
          (.text._vfprintf_r+0x2464): undefined reference to `_restfpr_31_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-vfprintf.o): in function `__sbprintf':
          (.text.__sbprintf+0xfc): undefined reference to `_restgpr_26_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-vfiprintf.o): in function `__sprint_r':
          (.text.__sprint_r+0xc8): undefined reference to `_restgpr_24_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-vfiprintf.o): in function `_vfiprintf_r':
          (.text._vfiprintf_r+0x13f4): undefined reference to `_restgpr_14_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-vfiprintf.o): in function `__sbprintf':
          (.text.__sbprintf+0xfc): undefined reference to `_restgpr_26_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libsysbase_libsysbase_a-sbrk.o): in function `_sbrk_r':
          (.text._sbrk_r+0x6e): undefined reference to `__end__'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: (.text._sbrk_r+0x72): undefined reference to `__end__'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-svfprintf.o): in function `_svfprintf_r':
          (.text._svfprintf_r+0x2338): undefined reference to `_restfpr_31_x'
          /opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/13.1.0/../../../../powerpc-eabi/bin/ld: /mnt/c/Users/antoi/Desktop/ogc-rs-master/examples/template/target/powerpc-unknown-eabi/debug/deps/libogc_sys-a4e1ebc8c0948490.rlib(libc_a-svfiprintf.o): in function `__ssprint_r':
          (.text.__ssprint_r+0x19c): undefined reference to `_restgpr_22_x'
          collect2: error: ld returned 1 exit status

**Comment by antoineok** [comment]
here are the complete logs:
https://hastebin.com/share/simucuxowo.vbnet

**Comment by antoineok** [comment]
the lib itself can be compiled without problem, but the exemples cannot compile

**Comment by ProfElements** [comment]
I can also confirm this tafter trying to figure it out for 4 hoursor so. if anyone has ideas im all ears

**Comment by antoineok** [comment]
so it's not just me who messed up the installation

**Comment by antoineok** [comment]
I've been looking, and it seems that _restfpr_31_x (the first undefined reference) is in devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/4.5.1\libgcc.a(crtresxfpr.o)

and __end__ doesn't exists

according to this source:
https://github.com/mrexodia/MAGIC1_fixer/blob/master/source/build/boot.elf.map

**Comment by antoineok** [comment]
and _vfprintf_r is from devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/4.5.1/../../../../powerpc-eabi/lib/libc.a(lib_a-vfprintf.o)

**Comment by antoineok** [comment]
Maybe the way it compiled changed, or the build argument changed, and this is why it doesn't work?

**Comment by antoineok** [comment]
basically, this is the command used while using the c template:

powerpc-eabi-gcc  template.o -g -DGEKKO -mrvl -mcpu=750 -meabi -mhard-float -Wl,-Map,template.elf.map -L/opt/devkitpro/libogc/lib/wii  -lwiiuse -lbte -logc -lm -o /opt/devkitpro/examples/wii/template/template.elf

**Comment by antoineok** [comment]
I noticed that those:
 -lwiiuse -lbte -logc -lm
 Weren't present in the command cargo used

**Comment by antoineok** [comment]
Still present in this version of ogc-rs
