### ISSUE TITLE
stdbool.h not found when compiling ogc-sys and LLVM's target data-layout changing

### ISSUE THREAD

**Issue by antoineok** [rust-wii/ogc-rs#89]
Hi again, 
I have two problems with your library.
The first one is a change in LLVM's default target:
`error: data-layout for target 'powerpc-unknown-eabi-6532891863323583425', 'E-m:e-p:32:32-i64:64-n32', differs from LLVM target's 'powerpc-unknown-eabi' default layout, 'E-m:e-p:32:32-Fn32-i64:64-n32'`
Replacing the data-layout in the json by the one said above seems to fix the issue.
The second one appears when compiling ogc-sys:
[Link to the error message](https://pastebin.com/j5TVaYSi)
I can send the error with the backtrace env variable set to 1 or full if asked.

**Comment by Daxorinator** [comment]
Thank you for your contribution to fix this - I see it's been merged so I'm going to close this issue and follow up on other PRs and issues to get the library working properly again
